name: Dependencies

on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "39 5 1,15 * *"
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  submit-dependencies:
    permissions:
      contents: write # required to submit dependencies report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0
      - name: Fetch version history
        if: (!startsWith(github.ref, 'refs/tags/'))
        run: git fetch --tag --unshallow
      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          dependency-graph: generate-and-submit
          gradle-home-cache-cleanup: true
      - name: Generate dependency report
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: runtimeClasspath
          DEPENDENCY_GRAPH_INCLUDE_PROJECTS: "^:(?!(buildSrc|test-)).*"
        run: ./gradlew allDeps --configuration runtimeClasspath
