name: Dependencies

on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "39 5 1,15 * *"
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  submit-dependencies:
    permissions:
      contents: write # required to submit dependencies report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2 # v2.1.1
      - name: Set up JDK
        uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3b1b3b9a2104c2b47fbae53f3938079c00c9bb87 # v3.0.0
        with:
          dependency-graph: generate-and-submit
          gradle-home-cache-cleanup: true
      - name: Generate dependency report
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: runtimeClasspath
          DEPENDENCY_GRAPH_INCLUDE_PROJECTS: "^:(?!(buildSrc|test-)).*"
        run: ./gradlew allDeps --configuration runtimeClasspath

