name: Dependencies

on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "39 5 1,15 * *"
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  submit-dependencies:
    permissions:
      contents: write # required to submit dependencies report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3b1b3b9a2104c2b47fbae53f3938079c00c9bb87 # v3.0.0
        with:
          dependency-graph: generate-and-submit
          gradle-home-cache-cleanup: true
      - name: Generate dependency report
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: runtimeClasspath
          DEPENDENCY_GRAPH_INCLUDE_PROJECTS: "^:(?!(buildSrc|test-)).*"
        run: ./gradlew allDeps --configuration runtimeClasspath

